/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InteropMain */

#ifndef _Included_InteropMain
#define _Included_InteropMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InteropMain
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_InteropMain_sum
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
